name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (Optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your secret token configured in Step 1
          token: ${{ secrets.METRICS_TOKEN }}

          # Options & Layout
          filename: github-metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi

          # 📊 PageSpeed Insights Plugin
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://portfolio-website-rahmankhattak.vercel.app # Replace with your live portfolio url
          plugin_pagespeed_detailed: no

          # 📅 Isometric Contributions Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # 💡 Coding Habits and Recent Activity
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # 🎵 Music Suggestions (Optional - set up if you use Apple Music/Spotify)
          plugin_music: no 
          plugin_music_provider: apple # Or spotify

          # 💻 Most Used Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
