name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs automatically every day
  workflow_dispatch: # Allows you to run it manually anytime
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Ensure this secret is added in repo settings

          # Core Layout Design
          filename: github-metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi

          # 📊 PageSpeed Insights Block
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://portfolio-website-rahmankhattak.vercel.app
          plugin_pagespeed_detailed: no

          # 📅 Isometric Contributions Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # 💡 Coding Habits Charts
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # 💻 Most Used Languages Block
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
